version: '3.9'
services:
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: body_order_password
    security_opt:
      - seccomp:unconfined
  app:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/body_order
    command: bash -c "rm -rf tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - mysql
    ports:
      - "3000:3000"

volumes:
  mysql-data:
